app:
    resource: '@AppBundle/Controller/'
    type: annotation

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

login:
    path:      /login
    defaults:  { _controller: AppBundle:Security:login }
 
logout:
    path:      /logout
    
user_registration:
    path:      /register
    defaults:  { _controller: AppBundle:Security:register }
    
admin:
    path: /admin
    defaults: { _controller: AppBundle:Default:admin }
    
homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }
    
homepage_locale:
    path:      /%app.route_prefix%/
    defaults:  { _controller: AppBundle:Default:index }
        
list:
    path:      /list/{what}/{howMany}
    defaults:  { _controller: AppBundle:Default:list, what: '%app.list_default%', howMany: '%app.list_rows%' }
    requirements:
        howMany: '\d+'
        
list_locale:
    path:      /%app.route_prefix%/list/{what}/{howMany}
    defaults:  { _controller: AppBundle:Default:list, what: '%app.list_default%', howMany: '%app.list_rows%' }
    requirements:
       howMany: '\d+'
       _locale: '%app.locales%'
       
entity_locale:
    path:      /%app.route_prefix%/entity/{what}/{id}
    defaults:  { _controller: AppBundle:Default:entity, what: '%app.list_default%', id: '0' }
    requirements:
       _locale: '%app.locales%'
       
entity_save:
    path:      /save/{what}/{id}
    defaults:  { _controller: AppBundle:Default:saveEntity, what: '%app.list_default%', id: '0' }
    
live_search:
    path:      /livesearch/{what}
    defaults:  { _controller: AppBundle:Default:liveSearch }